seed: 0
exp_name: severity_singletask

device:
  cuda_device: cuda:0
  gpu_num_workers: 6

data:
  cv: 5
  fold_dir: data/processed/BX/5 # folder where upload the CV splits at patient level
  model_dir: models/BX/5 # folder to save trained model
  report_dir: reports/BX/5 # folder to save results
  classes: # name of classes
    - A
    - B
    - C
    - D
    - E
    - F
  batch_size: 64
  modes:
    img:
      loader_name: custom_preprocessing
      img_dir: data/BRIXIA # path for the dicom directory
      box_file: data/BRIXIA/processed/box_data_BX.xlsx  # if equal to None do not select the bounding box
      mask_dir: data/BRIXIA/processed/masks  # if equal to None do not select lung
      img_dim: 256 # resize shape (square)
      preprocess:
        clahe: False
        filter: False
        clip: False
        masked: False
        bbox_resize: True

model:
  model_name: single
  task: severity
  pretrained: False # if this parameter is None, the model is trained from scratch
  dropout_rate: 0.25
  regression_type: area
  freezing: False

trainer:
  loss: mse
  warmup_epochs: 50 # number of epochs to warm up the model, if 0 the model the optimization starts from the first epoch
  optimizer:
    lr: 0.001 # initial learning rate
    weight_decay: 0.00001 # weight decay
  scheduler: # allow to change learning rate during training
    mode: min
    patience: 15 # if the validation loss do not improve for x epochs, the scheduler reduces the learning rate (lr*10^-1)
    min_lr: 1e-6
    factor: 0.7 # if the validation loss do not improve for x epochs, the scheduler reduces the learning rate (lr*10^-1)
  early_stopping: 50 # if the validation loss do not improve for x epochs stop training
  max_epochs: 300