seed: 0
exp_name: severity_singletask

device:
  cuda_device: cuda:0
  gpu_num_workers: 6

data:
  cv: 5
  fold_dir: data/processed/BX/5 # folder where upload the CV splits at patient level
  model_dir: models/BX/5 # folder to save trained model
  report_dir: reports/BX/5 # folder to save results
  classes: # name of classes
    - A
    - B
    - C
    - D
    - E
    - F

  modes:
    img:
      loader_name: custom_preprocessing
      img_dir: data/BRIXIA # path for the dicom directory
      box_file: data/BRIXIA/processed/box_data_BX.xlsx  # if equal to None do not select the bounding box
      mask_dir: data/BRIXIA/processed/masks  # if equal to None do not select lung
      img_dim: 256 # resize shape (square)
      preprocess:
        clahe: False
        filter: False
        clip: False
        masked: False
        bbox_resize: True



