seed: 0
exp_name: clinical_autoencoder

device:
  #cuda_device: cuda:0
  gpu_num_workers: 32

data:
  cv: 10
  fold_dir: ./data/processed/folds/10 # folder where upload the CV splits at patient level
  model_dir: ./models/10/clinical # folder to save trained model
  report_dir: ./reports/10/clinical # folder to save results
  classes: # name of classes
    - MILD
    - SEVERE
  batch_size: 32
  modes:
    clinical:
      data_file: ./data/processed/clinical_data.csv # clinical data file

model:
  model_name: fc
  pretrained:
  dropout_rate: 0.25

trainer:
  optimizer:
    lr: 0.0001 # initial learning rate
    weight_decay: 0.00001 # weight decay
  scheduler: # allow to change learning rate during training
    mode: min
    patience: 10 # if the validation loss do not improve for x epochs, the scheduler reduces the learning rate (lr*10^-1)
  early_stopping: 10 # if the validation loss do not improve for x epochs stop training
  max_epochs: 100
