seed: 0
exp_name: morbidity_singletask

device:
  cuda_device: cuda:0
  gpu_num_workers: 6

data:
  cv: 5
  fold_dir: data/processed/AFC/5 # folder where upload the CV splits at patient level
  model_dir: models/AFC/5 # folder to save trained model
  report_dir: reports/AFC/5 # folder to save results
  classes: # name of classes
    - MILD
    - SEVERE
  batch_size: 64
  modes:
    img:
      loader_name: custom_preprocessing
      img_dir: data/AIforCOVID # path for the dicom directory
      box_file: data/AIforCOVID/processed/box_data_AXF123.xlsx  # if equal to None do not select the bounding box
      mask_dir: data/AIforCOVID/processed/masks  # if equal to None do not select lung
      img_dim: 256 # resize shape (square)
      preprocess:
        clahe: False
        filter: False
        clip: False
        masked: True
        bbox_resize: True

model:
  freezing: False
  model_name: single
  task: morbidity
  pretrained: False # if this parameter is None, the model is trained from scratch
  dropout_rate: 0.25
  softmax: False # if True, the output is a probability distribution over the classes

trainer:
  loss: mse # loss function
  warmup_epochs: 50 # number of epochs to warm up the model, if 0 the model the optimization starts from the first epoch
  optimizer:
    lr: 0.001 # initial learning rate
    weight_decay: 0.00001 # weight decay
  scheduler: # allow to change learning rate during training
    mode: min
    patience: 15 # if the validation loss do not improve for x epochs, the scheduler reduces the learning rate (lr*10^-1)
    min_lr: 1e-6
    factor: 0.7 # if the validation loss do not improve for x epochs, the scheduler reduces the learning rate (lr*10^-1)
  early_stopping: 50 # if the validation loss do not improve for x epochs stop training
  max_epochs: 300
