seed: 0
exp_name: img_autoencoder_conv_1024

device:
  #cuda_device: cuda:1
  gpu_num_workers: 32

data:
  cv: 10
  fold_dir: ./data/processed/folds/10 # folder where upload the CV splits at patient level
  model_dir: ./models/10/img # folder to save trained model
  report_dir: ./reports/10/img # folder to save results
  classes: # name of classes
    - MILD
    - SEVERE
  batch_size: 32
  modes:
    img:
      loader_name: custom_preprocessing
      img_dir: ../data/AIforCOVID/imgs # path of img directory
      box_file: ./data/processed/box_data.xlsx  # if equal to None do not select the bounding box
      mask_dir: ../data/AIforCOVID/masks  # if equal to None do not select lung
      img_dim: 256 # resize shape (square)

model:
  model_name: conv
  pretrained:
  h_dim: 16384
  dropout_rate: 0.25

trainer:
  optimizer:
    lr: 0.001 # initial learning rate
    weight_decay: 0.00001 # weight decay
  scheduler: # allow to change learning rate during training
    mode: min
    patience: 10 # if the validation loss do not improve for x epochs, the scheduler reduces the learning rate (lr*10^-1)
  early_stopping: 300 # if the validation loss do not improve for x epochs stop training
  max_epochs: 300
